jobs:
- job: HostJob
  templateContext:
    outputs:
    - output: pipelineArtifact
      targetPath: $(Build.SourcesDirectory)/dist
      artifactName: artifactName
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'
  - task: PipAuthenticate@1
    displayName: 'Pip Authenticate'
    inputs:
      artifactFeeds: 'Lotus'
  - script: |
      python -m pip install --upgrade pip
      pip install -e .[test,lint]
    displayName: 'Install dependencies'

  - script: |
      lintrunner .
    displayName: 'Run lintrunner with RUFF'

  - script: |
      python -c "import onnxconverter_common"
      pytest tests --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'pytest - onnxutils'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'junit/test-results.xml'
      testRunTitle: 'Python 3.9'
    condition: succeededOrFailed()

  - script: |
      python -m pip install --upgrade pip
      pip install build
      python -m build
    displayName: 'Build Python Package'