jobs:
- job: HostJob
  templateContext:
    outputs:
    - output: pipelineArtifact
      targetPath: $(Build.SourcesDirectory)/dist
      artifactName: artifactName
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements-dev.txt      
      pip install -e .
    displayName: 'Install dependencies'

  - script: |
      lintrunner .
    displayName: 'Run lintrunner with RUFF'

  - script: |
      python -c "import onnxconverter_common"
      pytest tests --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'pytest - onnxutils'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'junit/test-results.xml'
      testRunTitle: 'Python 3.9'
    condition: succeededOrFailed()

  - task: CmdLine@2
    displayName: 'Command Line Script'
    inputs:
      script: |
        pip install --upgrade pip
        pip install wheel
        python setup.py bdist_wheel