# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:

- job: 'Linux'
  pool:
    vmImage: 'Ubuntu-latest'
  strategy:
    matrix:
      Python382:
        python.version: '3.8'
        ONNX_PATH: onnx==1.13.0

      Python391:
        python.version: '3.9'
        ONNX_PATH: onnx==1.13.0

      Python392:
        python.version: '3.9'
        ONNX_PATH: onnx==1.13.0

      Python310:
        python.version: '3.10'
        ONNX_PATH: onnx==1.14.0

    maxParallel: 4

  steps:
  - script: sudo install -d -m 0777 /home/vsts/.conda/envs
    displayName: Fix Conda permissions

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      addToPath: true
      architecture: 'x64'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip
      pip install protobuf
      pip install numpy
      pip install -r requirements.txt
      # install ORT dependencies
      pip install onnxruntime
      # replace with ort-nightly
      pip uninstall -y onnxruntime
      pip install --index-url https://test.pypi.org/simple/ ort-nightly
      pip install $(ONNX_PATH)
      pip install protobuf>=3.20.2
      pip install pytest
      pip install onnxmltools
      pip install -e .
    displayName: 'Install dependencies'

  - script: |
      pip install flake8
      python -m flake8 onnxconverter_common
    displayName: 'run flake8 check'

  - script: |
      python -c "import onnxconverter_common"
      pytest tests --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'pytest - onnxutils'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

- job: 'Win32'
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:
      Python382:
        python.version: '3.8'
        ONNX_PATH: onnx==1.13

      Python391:
        python.version: '3.9'
        ONNX_PATH: onnx==1.13

      Python392:
        python.version: '3.9'
        ONNX_PATH: onnx==1.13

      Python310:
        python.version: '3.10'
        ONNX_PATH: onnx==1.14

    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip numpy
      echo Test numpy installation... && python -c "import numpy"
      pip install -r requirements.txt
      # install ORT dependencies
      pip install onnxruntime
      # replace with ort-nightly
      pip uninstall -y onnxruntime
      pip install --index-url https://test.pypi.org/simple/ ort-nightly
      pip install %ONNX_PATH%
      pip install protobuf>=3.20.2
      pip install pytest
      pip install onnxmltools
      pip install -e .
    displayName: 'Install dependencies'

  - script: |
      pip install flake8
      python -m flake8 onnxconverter_common
    displayName: 'run flake8 check'

  - script: |
      call activate py$(python.version)
      pytest tests --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'pytest - onnxutils'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()


schedules:
- cron: "0 10 * * *"
  displayName: Daily onnxruntime nightly unittest
  branches:
    include:
    - master
  always: true
